system:
  gpu-id: 0
  traces: /data/pengmiao/ML-DPC-50/LoadTraces
  processed: /data/pengmiao/HPEC23/processed
  model: /data/pengmiao/HPEC23/model

apps:
  app: 473.astar-s1.txt.xz

teacher:
  number: 5
  models:
    - l
    - l
    - l
    - l
    - l
student:
  model: l

train:
  epochs: 50
  lr: 0.0002
  gamma: 0.1
  step-size: 20
  early-stop: 10
  alpha: 0.5
  temperature: 5

trace-data:
  train: 20
  total: 30
  skip: 1
  batch-size: 256

model:
  tch_d:
    channels: 1
  tch_r:
    channels: 1
  tch_v:
    channels: 1
    dim: 256
    depth: 8
    heads: 10
    mlp-dim: 256
  tch_m:
    channels: 1
    dim: 1024
    depth: 20
  tch_l:
    vocab-size: 20
    embed-dim: 300
    hidden-dim: 512
    num-layers: 10
  stu_d:
    channels: 1
  stu_r:
    channels: 1
  stu_v:
    channels: 1
    dim: 16
    depth: 2
    heads: 2
    mlp-dim: 16
  stu_m:
    channels: 1
    dim: 32
    depth: 2
  stu_l:
    vocab-size: 16
    embed-dim: 10
    hidden-dim: 50
    num-layers: 1
    
hardware:
  block-bits: 6
  total-bits: 64
  look-back: 9
  pred-forward: 128
  page-bits: 12
  delta-bound: 128
  split-bits: 6
  filter-size: 16
  bitmap-size: 256 # 2 * delta-bound
  block-num-bits: 58 # total-bits - block-bits
